# Usar una imagen oficial de Node.js ligera
FROM node:20-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de configuración de dependencias
COPY package*.json ./

# Instalar las dependencias de Node
RUN npm install

# Copiar el resto del código fuente de React
COPY . .

# Exponer el puerto por defecto de Vite
EXPOSE 5173

# Iniciar el servidor de desarrollo. 
# El flag "--host" es OBLIGATORIO en Docker para que Vite se exponga hacia la máquina local.
CMD ["npm", "run", "dev", "--", "--host"]